name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  pull_request_target:
    types:
      - closed

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This runs before the if"
      if: ${{ (github.event.pull_request.merged == true)}}
      - run: echo "This runs after the if"
